version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HOST_PORT}:80"
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: ["composer", "install"]

volumes:
  dbdata:
    driver: local

networks:
  laravel:
    driver: bridge
